export const incomeCategories = [
  { name: "Salary", subs: ["Base", "Overtime", "Commission", "Bonus", "13th Month", "Allowance"] },
  { name: "Allowance", subs: ["Family", "School", "Company"] },
  { name: "Freelance & Contract", subs: ["Consulting", "Design", "Development", "Writing"] },
  { name: "Business", subs: ["Sales", "Profit", "Capital Return"] },
  { name: "Investments", subs: ["Dividends", "Interest", "Stocks", "Bonds", "Mutual Funds", "Crypto"] },
  { name: "Rental Income", subs: ["Apartment", "Condo", "Parking"] },
  { name: "Refunds & Reimbursements", subs: ["Work", "Health", "Tax"] },
  { name: "Cashback & Rewards", subs: ["Credit Card", "E-wallet", "App Rewards"] },
  { name: "Stipend & Scholarship", subs: ["Stipend", "Scholarship", "Grant"] },
  { name: "Gifts", subs: ["Family", "Friends"] },
  { name: "Other", subs: ["Misc"] },
];

export const expenseCategories = [
  { name: "Food & Dining", subs: ["Groceries", "Restaurants", "Coffee", "Snacks", "Delivery"] },
  { name: "Transportation", subs: ["Fuel", "Public Transit", "Ride-hailing", "Parking", "Toll", "Maintenance"] },
  { name: "Shopping", subs: ["Clothes", "Gadgets", "Home", "Appliances"] },
  { name: "Housing", subs: ["Rent", "Mortgage", "Repairs", "HOA"] },
  { name: "Bills & Utilities", subs: ["Electricity", "Water", "Internet", "Mobile", "Cable/TV"] },
  { name: "Subscriptions", subs: ["Streaming", "Music", "Cloud", "Apps"] },
  { name: "Loans & Debt", subs: ["Loan Payment", "Credit Card", "Interest"] },
  { name: "Insurance", subs: ["Health", "Life", "Car", "Home"] },
  { name: "Health", subs: ["Medicines", "Checkup", "Gym"] },
  { name: "Education", subs: ["Books", "Courses", "Tuition"] },
  { name: "Kids & Family", subs: ["Allowance", "School", "Baby Needs"] },
  { name: "Pets", subs: ["Food", "Vet", "Grooming"] },
  { name: "Donations & Gifts", subs: ["Charity", "Gifts"] },
  { name: "Government & Taxes", subs: ["Taxes", "Fees", "Fines"] },
  { name: "Fees & Charges", subs: ["Bank Fees", "Service Fees", "Late Fees"] },
  { name: "Entertainment", subs: ["Movies", "Games", "Trips", "Events"] },
  { name: "Personal Care", subs: ["Salon", "Toiletries"] },
  { name: "Other", subs: ["Misc"] },
];

export const providers = [
  { value: "BPI", label: "BPI" },
  { value: "BDO", label: "BDO" },
  { value: "Metrobank", label: "Metrobank" },
  { value: "PNB", label: "PNB" },
  { value: "Chinabank", label: "Chinabank" },
  { value: "Security Bank", label: "Security Bank" },
  { value: "RCBC", label: "RCBC" },
  { value: "UnionBank", label: "UnionBank" },
  { value: "EastWest", label: "EastWest" },
  { value: "LandBank", label: "LandBank" },
  { value: "UCPB", label: "UCPB" },
  { value: "AUB", label: "AUB" },
  { value: "PSBank", label: "PSBank" },
  { value: "Maya", label: "Maya" },
  { value: "GCash", label: "GCash" },
  { value: "GrabPay", label: "GrabPay" },
  { value: "ShopeePay", label: "ShopeePay" },
];


